name: sam-ci

on:
  workflow_dispatch: {}   # manual run only

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-southeast-2
      STACK_NAME: finance-risk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Build (SAM)
        run: sam build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy (SAM)
        run: |
          sam deploy \
            --stack-name "${STACK_NAME}" \
            --resolve-s3 \
            --capabilities CAPABILITY_IAM \
            --no-confirm-changeset
